name: Python Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        make bootstrap
    - name: Build
      run: |
        make build
    - name: Unit Test and Coverage
      run: |
        make test-coverage

  acceptance-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        make bootstrap  

    - name: Run acceptance tests
      run: make test-acceptance 

    - name: Prepare results
      if: always()
      run: make prepare-results

    - name: Publish Tests
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test_results